# Generated by Django 6.0 on 2025-12-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
