# Generated by Django 6.0 on 2025-12-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_city_user_full_address_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='received_gift_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
